language: perl
perl:
   - "5.19"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

before_install:
   # Prevent "Please tell me who you are" errors for certain DZIL configs
   - git config --global user.name "TravisCI"

install:
   # Deal with all of the DZIL dependancies, quickly and quietly
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla Dist::Zilla::App::Command::cover
   - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
   - dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose --notest

script:
   - dzil smoke --release --author && dzil cover -test

after_success:
  # Send cover report to Coveralls.io
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - dzil cover -report coveralls

env: RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
